controller:
  admin:
    username: "admin"

    userKey: jenkins-admin-user
    passwordKey: jenkins-admin-password

    createSecret: true
    existingSecret: ""
  # disable running tasks on the built-in node
  numExecutors: 0
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"
  
  prometheus:
    enabled: true
    scrapeInterval: 60s
    scrapeEndpoint: /prometheus
  serviceAnnotations:
    prometheus.io/path: /prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  podAnnotations:
    prometheus.io/path: /prometheus
    prometheus.io/port: "http"
    prometheus.io/scrape: "true"

agent:
  resources:
    requests:
      cpu: "512m"
      memory: "512Mi"
    limits:
      cpu: "512m"
      memory: "512Mi"

persistence:
  enabled: true
  accessMode: "ReadWriteOnce"
  size: "8Gi"